security:
    encoders:
        Sorin\Bundle\RestaurantBundle\Entity\User:
            algorithm: bcrypt

    providers:
        sorin_user_provider:
            entity:
                class: SorinRestaurantBundle:User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            provider: sorin_user_provider
    access_control:
        - { path: ^/v1/restaurants, roles: ROLE_CUSTOMER }