security:
    encoders:
        Sorin\Bundle\RestaurantBundle\Entity\User:
            algorithm: bcrypt

    providers:
        sorin_user_provider:
            entity:
                class: SorinRestaurantBundle:User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            provider: sorin_user_provider
    access_control:
        - { path: ^/v1/restaurants, roles: ROLE_CUSTOMER }
        - { path: ^/v1/cancels, roles: ROLE_CUSTOMER }
        - { path: ^/v1/confirms, roles: ROLE_RESTAURANT_USER}
        - { path: ^/v1/declines, roles: ROLE_RESTAURANT_USER}
        - { path: ^/v1/customer/edit, roles: ROLE_CUSTOMER }
        - { path: ^/v1/customer/remove, roles: ROLE_CUSTOMER }